[package]
name = "hello-phext"
version = "0.2.5"
authors = ["Will Bickford <wbic16@gmail.com>"]
description = "A rust-native implementation of phext"
homepage = "https://phext.io/"
license = "MIT"
edition = "2021"

[dependencies]
rocket = "0.5.0"