[package]
name = "hello-phext"
version = "0.0.6"
authors = ["Will Bickford <wbic16@gmail.com>"]
description = "A rust-native implementation of phext"
license = "MIT"

[dependencies]
impl_new = "0.2.0"