[package]
name = "hello-phext"
version = "0.1.0"
authors = ["Will Bickford <wbic16@gmail.com>"]
description = "A rust-native implementation of phext"
license = "MIT"
edition = "2021"

[dependencies]
impl_new = "0.2.0"
rocket = "0.5.0"